In [3]:
import numpy as np

In [4]:
seed = 42

In [8]:
np.random.seed(seed)
for i in range(3):
    data = np.random.randn(3, 2)
    print(data)

[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]
[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]
[[ 0.24196227 -1.91328024]
 [-1.72491783 -0.56228753]
 [-1.01283112  0.31424733]]


In [9]:
np.random.seed(seed)
for i in range(3):
    data = np.random.randn(3, 2)
    print(data)

[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]
[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]
[[ 0.24196227 -1.91328024]
 [-1.72491783 -0.56228753]
 [-1.01283112  0.31424733]]


In [10]:
rng = np.random.default_rng(seed)
for i in range(3):
    data = rng.standard_normal((3, 2))
    print(data)

[[ 0.30471708 -1.03998411]
 [ 0.7504512   0.94056472]
 [-1.95103519 -1.30217951]]
[[ 0.1278404  -0.31624259]
 [-0.01680116 -0.85304393]
 [ 0.87939797  0.77779194]]
[[ 0.0660307   1.12724121]
 [ 0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826 ]]


In [11]:
rng = np.random.default_rng(seed)
for i in range(3):
    data = rng.standard_normal((3, 2))
    print(data)

[[ 0.30471708 -1.03998411]
 [ 0.7504512   0.94056472]
 [-1.95103519 -1.30217951]]
[[ 0.1278404  -0.31624259]
 [-0.01680116 -0.85304393]
 [ 0.87939797  0.77779194]]
[[ 0.0660307   1.12724121]
 [ 0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826 ]]
